;;; .user-lisp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from user-completion.el

(register-definition-prefixes "user-completion" '("completion-preview-active-mode-map" "my-icomplete-styles"))


;;; Generated autoloads from user-confirmations.el

(register-definition-prefixes "user-confirmations" '("yes-or-no-p"))


;;; Generated autoloads from user-display.el

(register-definition-prefixes "user-display" '("using-small-screen"))


;;; Generated autoloads from user-emacs-specifics.el

(register-definition-prefixes "user-emacs-specifics" '("using-elisp-italics"))


;;; Generated autoloads from user-file-backups.el

(register-definition-prefixes "user-file-backups" '("backup-directory"))


;;; Generated autoloads from user-git.el

(register-definition-prefixes "user-git" '("git"))


;;; Generated autoloads from user-grep.el

(register-definition-prefixes "user-grep" '("using-ripgrep"))


;;; Generated autoloads from user-notes.el

(register-definition-prefixes "user-notes" '("docket"))


;;; Generated autoloads from user-npm.el

(register-definition-prefixes "user-npm" '("-npm-" "project-npm"))


;;; End of scraped data

(provide '.user-lisp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; .user-lisp-autoloads.el ends here
